### ISSUE TITLE
Question for board thickness

### ISSUE THREAD

**Issue by AxelAhlborn** [dabonetn/ti99psu-replacement#1]
Hi!

What thickness should the board have?

Greetings Axel

**Comment by feltel** [comment]
I'm not the author but a normal user who just assembled a PCB. I had mine produced with a 1mm thickness. This is about as thick as the original PCB in my TI99/4A. Also this is the smallest size you can get without paying extra money.

**Comment by dabonetn** [comment]
I always use the default 1.6mm, feel free to experiment.
